### ISSUE TITLE
Broke the assembler

### ISSUE THREAD

**Issue by samczsun** [Storyyeller/Krakatau#114]
```
.version 52 0 
.class [0]
.super java/lang/Object 
.end class 
```

```
Krakatau  Copyright (C) 2012-16  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Processing file Test.j, 1/1 remaining
Traceback (most recent call last):
  File "C:\Users\Sam\IdeaProjects\Helios\Krakatau\Krakatau\assembler\parse.py", line 968, in assemble
    name, data = Parser(tokenizer).parseClass()
  File "C:\Users\Sam\IdeaProjects\Helios\Krakatau\Krakatau\assembler\parse.py", line 384, in parseClass
    return a.cls.assemble(a.error)
  File "C:\Users\Sam\IdeaProjects\Helios\Krakatau\Krakatau\assembler\assembly.py", line 244, in assemble
    name = self._getName()
  File "C:\Users\Sam\IdeaProjects\Helios\Krakatau\Krakatau\assembler\assembly.py", line 151, in _getName
    if cpool.slots[clsind].type != 'Class':
AttributeError: 'NoneType' object has no attribute 'type'
If you see this message, please file an issue at https://github.com/Storyyeller/Krakatau/issues, including the error message and the assembly file that caused the error.

Total time 0.0130000114441
```

**Comment by Storyyeller** [comment]
Good catch. Unfortunately, I'm having computer troubles at the moment, but I'll try to get it fixed as soon as I can.

**Comment by Storyyeller** [comment]
Should be fixed now.

**Comment by Storyyeller** [comment]
Hi, I'm contacting you because you have shown interest in the Krakatau assembler in the past. I am currently investigating adding Java 9 support, so I was wondering if you have any opinions or thoughts about syntax for the new features (mostly the Module attribute as the other additions are fairly trivial).
