### ISSUE TITLE
ImportError: No module named disassemble

### ISSUE THREAD

**Issue by gnom7** [Storyyeller/Krakatau#126]
Hello, I get the following error
```
	at org.python.core.Py.ImportError(Py.java:328)
	at org.python.core.imp.import_first(imp.java:877)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at org.python.pycode._pyx0.f$0(<string>:1)
	at org.python.pycode._pyx0.call_function(<string>)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)
	at com.alexkasko.krakatau.KrakatauLibrary.disassemble(KrakatauLibrary.java:116)
	... 38 more
```
when running my app with
```
        <dependency>
            <groupId>com.alexkasko.krakatau</groupId>
            <artifactId>krakatau-lib</artifactId>
            <version>1.1</version>
        </dependency>
```
The same error `ImportError: No module named assemble` is for assemble call.
I have Python 2.7.14 installed.
Please any thoughts why this may happen?

**Comment by Storyyeller** [comment]
Can you reproduce this by running Krakatau with Python directly? Otherwise, it is likely an issue with the way it was bundled in whatever tool you are using.

**Comment by gnom7** [comment]
When I call Krakatau directly via python like this:
`Krakatau/disassemble.py -out $(pwd) -r $(pwd)/com`
all works just well.
But when I use [this](https://mvnrepository.com/artifact/com.alexkasko.krakatau/krakatau-lib/1.1) artifact from maven repo and call library from java code it fails to find module, may be some sort of additional pre-configuration is needed to work with Krakatau directly from java?

**Comment by gnom7** [comment]
I have just noticed that there is no releases in this repository, and that there is no java binding to the Krakatau, sorry, It seemed to me that artifact I use was official one.

**Comment by Storyyeller** [comment]
Sorry, you'll have to take it up with whoever maintains the Java bindings you're using.

**Comment by gnom7** [comment]
Sure, sorry again.
