### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by i0xHeX** [Storyyeller/Krakatau#143]
Errors with print trying to decompile:
```
Traceback (most recent call last):
  File "..\decompile.py", line 8, in <module>
    import Krakatau.ssa
  File "C:\Users\LuckyZeeRo\Desktop\Krakatau Assembler Java 9\Krakatau\ssa\__init__.py", line 1, in <module>
    from .graph import ssaFromVerified
  File "C:\Users\LuckyZeeRo\Desktop\Krakatau Assembler Java 9\Krakatau\ssa\graph.py", line 577
    print 'Warning, nesting subprocedures detected! This method may take a long time to decompile.'
                                                                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print 'Warning, nesting subprocedures detected! This method may take a long time to decompile.')?
```
Python 3.7.0a2
Seems it's for old Python. New syntax be like `print("text")`

**Comment by Janmm14** [comment]
did you used python 2.x?

**Comment by i0xHeX** [comment]
No, I didn't
I have Python 3.7.0a2 installed

**Comment by Janmm14** [comment]
Then that's the problem, decompilation process just supports python 2.x

**Comment by Storyyeller** [comment]
As mentioned by Janmm, the decompiler only supports Python 2. The assembler and disassembler support both Python 2 and Python 3.
