### ISSUE TITLE
Error while Decompiling

### ISSUE THREAD

**Issue by SecurityFlaw** [Storyyeller/Krakatau#168]
Loading com/sun/net/ssl/internal/ssl/Provider
Traceback (most recent call last):
  File "/home/mobaxterm/krakatau/decompile.py", line 158, in <module>
    decompileClass(path, targets, args.out, args.skip, magic_throw=args.xmagicthrow)
  File "/home/mobaxterm/krakatau/decompile.py", line 103, in decompileClass
    source = printer.visit(javaclass.generateAST(c, makeGraphCB, skip_errors, add_throws=add_throws))
  File "/home/mobaxterm/krakatau/Krakatau/java/javaclass.py", line 67, in generateAST
    method_defs = [_getMethod(m, cb, forbidden_identifiers, skip_errors) for m in methods]
  File "/home/mobaxterm/krakatau/Krakatau/java/javaclass.py", line 39, in _getMethod
    code_ast = javamethod.generateAST(method, graph, forbidden_identifiers)
  File "/home/mobaxterm/krakatau/Krakatau/java/javamethod.py", line 881, in generateAST
    _preorder(ast_root, partial(_addCastsAndParens, env=env))
  File "/home/mobaxterm/krakatau/Krakatau/java/javamethod.py", line 137, in _preorder
    val = func(scope, item)
  File "/home/mobaxterm/krakatau/Krakatau/java/javamethod.py", line 732, in _addCastsAndParens
    item.addCastsAndParens(env)
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 32, in addCastsAndParens
    self.expr.addCasts(env)
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 352, in addCasts
    self.addCasts_sub(env)
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 660, in addCasts_sub
    expr = makeCastExpr(tt, expr, fixEnv=env)
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 314, in makeCastExpr
    ret = ret.fix(fixEnv)
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 462, in fix
    if not isJavaAssignable(env, expr.dtype, tt):
  File "/home/mobaxterm/krakatau/Krakatau/java/ast.py", line 287, in isJavaAssignable
    return objtypes.isSubtype(env, fromt, to)
  File "/home/mobaxterm/krakatau/Krakatau/ssa/objtypes.py", line 54, in isSubtype
    return isBaseTClass(x) and isBaseTClass(y) and env.isSubclass(xname, yname)
  File "/home/mobaxterm/krakatau/Krakatau/environment.py", line 36, in isSubclass
    name1 = self._getSuper(name1)
  File "/home/mobaxterm/krakatau/Krakatau/environment.py", line 18, in _getSuper
    return self.getClass(name).supername
  File "/home/mobaxterm/krakatau/Krakatau/environment.py", line 24, in getClass
    result = self._loadClass(name)
  File "/home/mobaxterm/krakatau/Krakatau/environment.py", line 90, in _loadClass
    raise ClassLoaderError('ClassNotFoundException', name)
Krakatau.error.ClassLoaderError:
ClassNotFoundException: com/sun/net/ssl/internal/ssl/Provider

What's happening here?

**Comment by SecurityFlaw** [comment]
Problem solved, just download "com.sun.net.ssl.jar" and add to -path.
