### ISSUE TITLE
How to decompile single class file?

### ISSUE THREAD

**Issue by breezewish** [Storyyeller/Krakatau#31]
```
breezewish:lib breeswish$ python Krakatau/decompile.py ~/hello.class
Krakatau  Copyright (C) 2012-14  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Attempting to automatically locate the standard library...
Found at  /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre/lib/rt.jar
processing target /Users/breeswish/hello, 1 remaining
Loading /Users/breeswish/hello
Traceback (most recent call last):
  File "Krakatau/decompile.py", line 147, in <module>
    decompileClass(path, targets, args.out, plugins, args.skip)
  File "Krakatau/decompile.py", line 88, in decompileClass
    c = e.getClass(target)
  File "/Users/breeswish/Development/java-decompiler-combination/lib/Krakatau/Krakatau/environment.py", line 26, in getClass
    result = self._loadClass(name, subclasses)
  File "/Users/breeswish/Development/java-decompiler-combination/lib/Krakatau/Krakatau/environment.py", line 60, in _loadClass
    raise ClassLoaderError('ClassNotFoundException', name)
Krakatau.error.ClassLoaderError: 
ClassNotFoundException: /Users/breeswish/hello
```

**Comment by Storyyeller** [comment]
I'm planning to support decompilation of lone classfiles in the v2 decompiler (if I ever manage to write that), so I'm going to go ahead and close this now.
