### ISSUE TITLE
decompilation error

### ISSUE THREAD

**Issue by n0way0ut** [Storyyeller/Krakatau#58]
hello,
when I try to decompile a test .class file I receive:

$ ./decompile.py -path tests/classes/ DuplicateInit.class
Krakatau  Copyright (C) 2012-15  Robert Grosse
This program is provided as open source under the GNU General Public License.
See LICENSE.TXT for more details.

Attempting to automatically locate the standard library...
Unable to find the standard library
processing target DuplicateInit, 1 remaining
Loading DuplicateInit
Loading java/lang/Object
failed to open tests/classes/java/lang/Object.class
Traceback (most recent call last):
  File "./decompile.py", line 152, in <module>
    decompileClass(path, targets, args.out, args.skip)
  File "./decompile.py", line 98, in decompileClass
    c = e.getClass(target)
  File "/home/gian/tools/decompilers/Krakatau/Krakatau/environment.py", line 23, in getClass
    result = self._loadClass(name, subclasses)
  File "/home/gian/tools/decompilers/Krakatau/Krakatau/environment.py", line 71, in _loadClass
    new.loadSupers(self, name, subclasses)
  File "/home/gian/tools/decompilers/Krakatau/Krakatau/classfile.py", line 102, in loadSupers
    superclass = self.env.getClass(self.supername, subclasses + (name,), partial=True)
  File "/home/gian/tools/decompilers/Krakatau/Krakatau/environment.py", line 23, in getClass
    result = self._loadClass(name, subclasses)
  File "/home/gian/tools/decompilers/Krakatau/Krakatau/environment.py", line 67, in _loadClass
    raise ClassLoaderError('ClassNotFoundException', name)
Krakatau.error.ClassLoaderError: 
ClassNotFoundException: java/lang/Object

**Comment by samczsun** [comment]
Krakatau couldn't find rt.jar, so you'll need to specify the location of it in your path

**Comment by n0way0ut** [comment]
it worked. thanks.
